### ISSUE TITLE
Segmentation faults on `osx`

### ISSUE THREAD

**Issue by jchodera** [Amber-MD/ambertools-binary-build#12]
I've been seeing a number of sporadic segmentation faults on `osx` (10.12.6, MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)) using `ambertools` 17.5 installed from http://ambermd.org/downloads/ambertools/conda 
```
lski2414:amber choderaj$ tleap -f leap.in 
-I: Adding /Users/choderaj/miniconda/dat/leap/prep to search path.
-I: Adding /Users/choderaj/miniconda/dat/leap/lib to search path.
-I: Adding /Users/choderaj/miniconda/dat/leap/parm to search path.
-I: Adding /Users/choderaj/miniconda/dat/leap/cmd to search path.
-f: Source leap.in.

Welcome to LEaP!
(no leaprc in search path)
Sourcing: ./leap.in
----- Source: /Users/choderaj/miniconda/dat/leap/cmd/leaprc.ffAM1
----- Source of /Users/choderaj/miniconda/dat/leap/cmd/leaprc.ffAM1 done
Log file: ./leap.log
Loading parameters: /Users/choderaj/miniconda/dat/leap/parm/parmAM1.dat
Reading title:
PARMAM1 for proteins to reproduce semiempirical geometries
Loading library: /Users/choderaj/miniconda/dat/leap/lib/all_nucleic94.lib
Loading library: /Users/choderaj/miniconda/dat/leap/lib/all_aminoAM1.lib
/Users/choderaj/miniconda/bin/tleap: line 10: 43304 Segmentation fault: 11  $AMBERHOME/bin/teLeap -I$AMBERHOME/dat/leap/prep -I$AMBERHOME/dat/leap/lib -I$AMBERHOME/dat/leap/parm -I$AMBERHOME/dat/leap/cmd $*
```
Here's the `leap.in`:
```
source leaprc.ffAM1
x = loadPdb ala3.pdb
saveAmberParm x a b
quit
```
and `ala3.pdb`:
```
REMARK   1 CREATED WITH OPENMM 7.0, 2016-01-15
ATOM      1  N   ALA A   1       0.024  -0.103  -0.101  1.00  0.00           N  
ATOM      2  H1  ALA A   1       0.027  -1.132  -0.239  1.00  0.00           H  
ATOM      3  H2  ALA A   1      -0.805   0.163   0.471  1.00  0.00           H  
ATOM      4  H3  ALA A   1      -0.059   0.384  -1.019  1.00  0.00           H  
ATOM      5  CA  ALA A   1       1.247   0.375   0.636  1.00  0.00           C  
ATOM      6  HA  ALA A   1       0.814   0.861   1.495  1.00  0.00           H  
ATOM      7  CB  ALA A   1       2.057  -0.772   1.289  1.00  0.00           C  
ATOM      8  HB1 ALA A   1       3.136  -0.752   1.032  1.00  0.00           H  
ATOM      9  HB2 ALA A   1       1.990  -0.641   2.395  1.00  0.00           H  
ATOM     10  HB3 ALA A   1       1.656  -1.782   1.063  1.00  0.00           H  
ATOM     11  C   ALA A   1       1.956   1.579   0.036  1.00  0.00           C  
ATOM     12  O   ALA A   1       1.219   2.525  -0.201  1.00  0.00           O  
ATOM     13  N   ALA A   2       3.289   1.631  -0.202  1.00  0.00           N  
ATOM     14  H   ALA A   2       3.939   0.868  -0.174  1.00  0.00           H  
ATOM     15  CA  ALA A   2       3.990   2.909  -0.215  1.00  0.00           C  
ATOM     16  HA  ALA A   2       3.742   3.440   0.695  1.00  0.00           H  
ATOM     17  CB  ALA A   2       3.662   3.802  -1.434  1.00  0.00           C  
ATOM     18  HB1 ALA A   2       4.192   4.778  -1.358  1.00  0.00           H  
ATOM     19  HB2 ALA A   2       3.956   3.311  -2.382  1.00  0.00           H  
ATOM     20  HB3 ALA A   2       2.577   4.027  -1.467  1.00  0.00           H  
ATOM     21  C   ALA A   2       5.487   2.654  -0.128  1.00  0.00           C  
ATOM     22  O   ALA A   2       5.889   1.489  -0.137  1.00  0.00           O  
ATOM     23  N   ALA A   3       6.275   3.733  -0.037  1.00  0.00           N  
ATOM     24  H   ALA A   3       5.963   4.691  -0.028  1.00  0.00           H  
ATOM     25  CA  ALA A   3       7.707   3.802   0.068  1.00  0.00           C  
ATOM     26  HA  ALA A   3       8.160   3.418  -0.833  1.00  0.00           H  
ATOM     27  CB  ALA A   3       8.233   3.093   1.333  1.00  0.00           C  
ATOM     28  HB1 ALA A   3       9.342   3.149   1.356  1.00  0.00           H  
ATOM     29  HB2 ALA A   3       7.835   3.593   2.240  1.00  0.00           H  
ATOM     30  HB3 ALA A   3       7.923   2.030   1.332  1.00  0.00           H  
ATOM     31  C   ALA A   3       8.018   5.323   0.136  1.00  0.00           C  
ATOM     32  O   ALA A   3       7.032   6.119   0.127  1.00  0.00           O  
ATOM     33  OXT ALA A   3       9.219   5.692   0.188  1.00  0.00           O  
TER      34      ALA A   3
END
```
I'm guessing it has something to do with this particular build of `ambertools` for conda.

**Comment by hainm** [comment]
Thanks. Will investigate.

Is it ok with 17.4?

**Comment by jchodera** [comment]
This is quite strange. I see spontaneous random segfaults on all the `ambertools` I was able to install (17.0, 17.1, 17.3, 17.4, 17.5). I also see much less frequent segfaults with `ambermini` (about one in twenty runs). I'll see if I can track this down a bit further.

**Comment by hainm** [comment]
Thanks for trying. I only see the segmentation fault with clang before, but
i used gnu in this case. Weird.

**Comment by hainm** [comment]
uhm, freaking weird. I can reproduce your issue with my mac. However, it's fine If I replace "leaprc.ffAM1" with "leaprc.protein.ff14SB".

**Comment by hainm** [comment]
@dacase I've been trying with master branch with MacOS, either clang and GNU compiler (from /usr/local/gfortran/bin (suggested from ambermd.org); just doing normal build (without conda-build) The segmentations faults still happens sometimes (tried 10 times and got 4-6/10).

@jchodera I've updated your 1st post to change "files/villin.pdb" to "ala3.pdb" (what you meant, right?).

**Comment by hainm** [comment]
@dacase can you try with @jchodera system in 1st post in your mac? (10 times?). thanks.

**Comment by hainm** [comment]
Uhm, try to replace "leaprc.ffAM1" with "leaprc.protein.ff14SB" again and run 10 times, all are ok.

**Comment by hainm** [comment]
tleap on Linux is ok with @jchodera  system.

**Comment by jchodera** [comment]
> @jchodera I've updated your 1st post to change "files/villin.pdb" to "ala3.pdb" (what you meant, right?).

The `ala3.pdb` I provided sporadically, but it seems to fail with much higher frequency with something larger like `villin.pdb`.

**Comment by jchodera** [comment]
> Uhm, try to replace "leaprc.ffAM1" with "leaprc.protein.ff14SB" again and run 10 times, all are ok.

You're right---ff14SB is rock-stable! This is for our [AMBER/CHARMM forcefield conversion for OpenMM](https://github.com/choderalab/openmm-forcefields), so we'll need to make it work somehow (though it seems to work fine on linux).

**Comment by hainm** [comment]
I go ahead closing this issue. I've been testing with ambertools-18 and there is only 1/50 chance of getting segmentation fault. It's good for now. Cheers.

**Comment by jchodera** [comment]
Does that mean ambertools-18 will still occasionally give a segfault? 

Just asking so we know how to wrap it in our code to make our pipelines robust.

**Comment by hainm** [comment]
On Thu, May 3, 2018 at 9:02 AM, John Chodera <notifications@github.com>
wrote:

> Does that mean ambertools-18 will still occasionally give a segfault?
>
> Just asking so we know how to wrap it in our code to make our pipelines
> robust.
>

yeah, I've tried 50 times with your input and command, only 1 failed. :D

**Comment by jchodera** [comment]
Eep---one failure is still more than zero, so we still have to wrap it in some sort of `try...except` clause and rerun it until it works. Do you happen to know if the segfault can easily be caught from Python?

**Comment by hainm** [comment]
unfortunately I don't know.
