### ISSUE TITLE
How can I learn how to make conda installation tarballs

### ISSUE THREAD

**Issue by dacase** [Amber-MD/ambertools-binary-build#14]
@hainm 

How can I start to learn how to make a conda recipe for a subset of AmberTools code?

Specifically, I'd like to get a conda package for the code here:

    https://www.dropbox.com/s/plu2izlrdyu5dxw/amber_phenix-0.8.tar.bz2?dl=0

This is the (small) subset of AmberTools needed for phenix.  As I see it, I need to learn:
   (a) how to build the code on a "generic" Linux and MacOSX platform
   (b) how to create the .json files that describe the distribution to conda
   (c) how to name the files, and where to put them (say on the ambermd web site) so that a 
```
conda install -c ??? amber-phenix
``` 
command can be used to get them.

Are there other key steps I'm missing?  What is a good place to learn how to do this?

...thx...dac

**Comment by hainm** [comment]
hi @dacase,
I've made a recipe for you to play it. 
[recipe.txt](https://github.com/Amber-MD/ambertools-binary-build/files/2867569/recipe.txt)

- Download `recipe.txt` and rename .txt to .tar
- tar xf recipe.tar
- Update amber_phenix-0.8 path in recipe/meta.yaml
- Run conda build vai
```
conda build ./recipe
# Update build.sh to your need
```

You can find the final built tar file in the very end of log message, something like:
```
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /Users/haichit/miniconda3/conda-bld/osx-64/amber_phenix-0.8-0.tar.bz2
```

You can update build time and run time dependency in the meta.yaml file (https://conda.io/projects/conda-build/en/latest/source/define-metadata.html)

**Comment by hainm** [comment]
> (a) how to build the code on a "generic" Linux and MacOSX platform

You need to run above steps on a Linux machine to get a Linux distribution and so on for MacOS.
For ambertools, I am using a docker image of centos 5 so ambertools can be used for most Linux distros.

> b) how to create the .json files that describe the distribution to conda
> (c) how to name the files, and where to put them (say on the ambermd web site) so that a conda `install -c ??? amber-phenix`

For (b) and (c), you can copy the build files (for Linux and MacOS) to corresponding folder in rcsb server. The should be in the same folder as ambertools binary.
`<the path in rcsb>/downloads/ambertools/conda/{osx-64,linux-64}`

To update the .json file for each platform, you need to
```
# linux
cd <the path in rcsb>/downloads/ambertools/conda/linux-64
conda index . # update .json file
```

Now, you can try:
```
conda install amber_phenix -c http://ambermd.org/downloads/ambertools/conda/
```

> (c) how to name the files,

Just update the package name in `meta.yaml` and rerun the build process.

PS: For experimenting, I suggest to make the amber_phenix build quick.

**Comment by hainm** [comment]
> What is a good place to learn how to do this?

My above replies. :D 

For further information, you can read the conda-build docs: 
- https://conda.io/projects/conda-build/en/latest/source/sample-recipes.html
- https://conda.io/projects/conda-build/en/latest/source/recipe.html

Please let me know if you need further help. Cheers.

**Comment by hainm** [comment]
... or if I miss any of your comments.

**Comment by dacase** [comment]
I'm having trouble with the recipe/build.sh script.  Here is what I have:
```
#!/bin/sh

export AMBERHOME=`pwd`
./configure
make install -j4

PREFIX=/home/case/amber_phenix-0.9_build
rsync -av bin dat $PREFIX
```

Above all gets done, and the correct material gets rsync-ed to the the PREFIX directory, but "conda build" doesn't seem to know about $PREFIX, and so builds an empty tarball.  So, what should $PREFIX be, and how do I tell conda build where this is?

**Comment by hainm** [comment]
hi @dacase,

you only need to update the path to the amber_phenix source code, nothing else. `$PREFIX` is reserved variable(`PREFIX` appears to be used to refer to the directory of the current conda environment.", just keep the `build.sh` as it is. conda-build will handle all the thing and will give you the final tar file.

**Comment by hainm** [comment]
Further reading: https://conda.io/projects/conda-build/en/latest/source/environment-variables.html

**Comment by dacase** [comment]
Thanks for the comment about PREFIX.  Looks like I'm getting close....

**Comment by hainm** [comment]
yay

**Comment by dacase** [comment]
Hai: how have handled the lack of static binaries on Mac?  If I compile a pure C program (like teLeap) with Apple's clang, then otool -l indicates that it is only linked to system libraries, and might therefore be portable to lots of machines.

But a fortran program like sander is always going to link to some fortran library, e.g.
/usr/local/gfortran/lib/libgfortran.5.dylib.  I have the .a version of that library, but not for others that are needed.  So, what's the trick to get an OSX binary to users who won't have /usr/local/gfortran on their machines?

**Comment by hainm** [comment]
For AmberTools, I wrote a script to fix the linking and copy gfortrab library to ambertools.

- Download the whole `conda_tools` folder (or just git clone ambertools-binary-build repo): https://github.com/Amber-MD/ambertools-binary-build/tree/master/conda_tools
- Update `fix_conda_gfortran_linking_osx.py` by changing this line:
https://github.com/Amber-MD/ambertools-binary-build/blob/7032656277f1d7cdd6060a3f140dc7c5dc8eccd1/conda_tools/fix_conda_gfortran_linking_osx.py#L31

to 
`
update_gfortran_libs_osx.main(['.', '--copy-gfortran'])
`

- Run
```bash
python ambertools-binary-build/conda_tools/fix_conda_gfortran_linking_osx.py your_conda_package -o a_folder # This will do all the work and write a new conda pakcage.
```

But you might want to try to add gfortran dependency at build and run time. e.g: add ["gfortran_osx-64 ](https://anaconda.org/anaconda/gfortran_osx-64) to [requirement](https://conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html#requirements-section) in `meta.yaml` (I have not tried yet).

**Comment by hainm** [comment]
If you used my script, here is example:

```
$ otool  -L ./sander
./sander:
	@rpath/amber_3rd_party/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	@rpath/amber_3rd_party/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/amber_3rd_party/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

And you can see 
```
$ ls lib/amber_3rd_party/
libgcc_s.1.dylib    libgfortran.3.dylib libquadmath.0.dylib libstdc++.6.dylib
```

Sander seems running fine
```
$ ./sander

  Error opening unit    6: File "mdout" exists (use -O to overwrite)      
```

**Comment by dacase** [comment]
Hai: thanks for the all the detailed help...would have taken forever for me to figure this out just from the anaconda documentation.

OK: getting close.  Potential problem is that the executables that get modified by fix_conda_gfortran_linking  then generate a "SafetyError" for the users:
```
SafetyError: The package for amber_phenix located at /home/case/amber18/miniconda/pkgs/amber_phenix-0.9-0
appears to be corrupted. The path 'bin/addles'
has a sha256 mismatch.
  reported sha256: 95053830b8e0648e758c81af2651413b7f38d8d7469965e2053e4f4e06f93664
  actual sha256: 6203d243aef7559a1f2c5e26d118560566407418b7f91e52e2504279c9ed33b4
```

This message appears for each of the fortran-related executables, not for the others.  I'm guessing that this is becuase the script modified the executable after conda built it.  This would be something worth dealing with (i.e. getting rid of) if we can.

But the general procedure seems to be working, at least for MacOSX (minimal testing so far). Next, on to Linux.  And I'm thinking of making a "noarch" package with the source and build instructions: have you ever looked at this.

**Comment by hainm** [comment]
> Next, on to Linux.

yeah, just build the package on a Linux machine (preferably centos 5 or 6).
You can also use docker to run on your Mac. Please download the attach script (rename *.txt to *.sh) then 

[run_docker_build.txt](https://github.com/Amber-MD/ambertools-binary-build/files/2873777/run_docker_build.txt)

```
- cd to folder having `recipe` and `amber-phenix` folders.
- bash run_docker_build.sh # require to install docker on Mac.
```

The output binary will be in `./linux-64-build`. Do feel free to play with the `run_docker_build.sh` script and let me know if you have any question.

> And I'm thinking of making a "noarch" package with the source and build instructions: have you ever looked at this?

do you mean something like `amber_phenix_source.bz2`? What's the aim of this?

**Comment by dacase** [comment]
Hai asked 
```
do you mean something like `amber_phenix_source.bz2`? What's the aim of this?
```

1.  source code distribution is smaller, and might be needed if the binary code doesn't work, say on some particular variant of Linux or OSX.
2.  some great volunteer could get this build on Windows, so we could then make a binary distribution for that platform
3. users can and will look at the source code and suggest fixes or improvements; a binary-only distribution is just a black box.

**Comment by hainm** [comment]
In this case, I think referring user to a direct link on amber website is easier. `conda install` will populate the source code in miniconda distribution path and I don't think that's a good place to read the source.

Of course, it would be helpful if `conda` has option like `conda download something` without installing.

**Comment by hainm** [comment]
uhm, new conda has `--download-only` but I have not tried that yet.
https://github.com/conda/conda/pull/5988

**Comment by dacase** [comment]
About the "SafetyError" problem mentioned above:

This can indeed be cirumvented by running the script to fix the @rpath issue inside build.sh, before the executables are copied to PREFIX.  Updated recipe/build.sh has been pushed to gitlab.

**Comment by hainm** [comment]
You're right.
I've been doing that for AmberTools binary too. https://github.com/Amber-MD/ambertools-binary-build/blob/master/conda-ambertools-all-python/build_ambertools.py#L44

**Comment by hainm** [comment]
> How can I learn how to make conda installation tarballs

Resolved.
