### ISSUE TITLE
comments on the new, "simplified" tree

### ISSUE THREAD

**Issue by dacase** [Amber-MD/ambertools-binary-build#18]
Hai:

Thanks for putting this together!  Here are a few comments about the current contents:

* I think the `conda-ambermini-recipe` folder is outdated, and should be deleted.  For one thing, I have confiscated the `ambermini` name to mean something different than it used to, and I have my own set to conda recipes there (see the `ambermini` repo at gitlab.)  So talking about `ambermini` here is just going to cause confusion.

* Do we still need the `conda-ambertools-all-python` folder?  If so, could it be moved to an `old` directory, or some similar name?  It doesn't seem to be used by `build_all_simplified.sh`. I'm trying to keep the clutter down, so that when I (or others) come back in a few months, we can focus immediately on the key files.

* Same question for lots of other folders that appear not to be current.  Just pushing them down into an `old` folder would be a big win--reducing potential confusion, yet not really losing old stuff that might still be useful.

* The `README.md` file in the `conda-recipe` folder seems likewise pretty outdated.

I think you see the overall point.  But don't get rid of anything that is truly still useful!

...thx...dac

**Comment by dacase** [comment]
Second comment:  a good goal would be to simplify the requirements section in the `meta.yaml` file.
Getting rid of `libgcc [linux]` should be possible if `-static` is used for linux compilation. Other requirements may also not be needed--we'll have to play around.  The idea is this: the fewer the requirements, the easier it is on users and the easier it is for the resulting tar file to be used outside of a `conda` environment.

**Comment by hainm** [comment]
hi @dacase, 
> I think the conda-ambermini-recipe folder is outdated, and should be deleted

deleted.

> Do we still need the conda-ambertools-all-python folder? If so, could it be moved to an old directory, or some similar name? It doesn't seem to be used by build_all_simplified.sh. I'm trying to keep the clutter down, so that when I (or others) come back in a few months, we can focus immediately on the key files.

Yes, we need `conda-ambertools-all-python` and you can see it in the build script. However, I've renamed it to `conda-ambertools-combine-pythons` (please see the comment inside the build script again).

> Same question for lots of other folders that appear not to be current. Just pushing them down into an old folder would be a big win--reducing potential confusion, yet not really losing old stuff that might still be useful.

deleted/moved some of them.

> The README.md file in the conda-recipe folder seems likewise pretty outdated.

deleted. PS: I've changed "conda-recipe" to `conda-ambertools-single-python`. This recipe is doing what its name suggests, to build full ambertools with specific python version.

> Second comment: a good goal would be to simplify the requirements section in the meta.yaml file.
Getting rid of libgcc [linux] should be possible if -static is used for linux compilation. Other requirements may also not be needed--we'll have to play around. The idea is this: the fewer the requirements, the easier it is on users and the easier it is for the resulting tar file to be used outside of a conda environment.

I agree. I've removed 'libgcc[linux] and we don't need `-static`. I might try with `-static` to see if we can build AT with gcc-5 and use it with centos-6 (gcc-4) or not.

The final ambertools does not have any requirement at run time: https://github.com/Amber-MD/ambertools-binary-build/blob/master/conda-ambertools-combine-pythons/meta.yaml
NOTE: I do not specify python version so ambertools can be installed with any python version.

**Comment by hainm** [comment]
Let me know if I miss any of your comments.

PS: You can test the build process by using the mocked "fake_amber" folder.

```
cd ambertools-binary-build
bash build_all_simplified.sh conda_tools/test/fake_amber .
```
The aim here is to **quickly** (~ 4 minutes) test the build workflow and not test the process of compiling the real AT itself.

**Comment by hainm** [comment]
** Build bugfix version**

The build process always run `update_amber`, so to build the bugfix version (e.g: `v19.1`), you only need to update the `bugfix_version ` version (latest bugfix number) in `meta.yaml` (https://github.com/Amber-MD/ambertools-binary-build/blob/master/conda-ambertools-combine-pythons/meta.yaml) and rerun the `build_all_simplified.sh` again.

**Comment by dacase** [comment]
Thanks!  I'll play with this some, but not until next week sometime.

**Comment by hainm** [comment]
This can be closed now. cheers.
