### ISSUE TITLE
Issue with XLEAP! 

### ISSUE THREAD

**Issue by tangkallisbak1** [Amber-MD/ambertools-binary-build#19]
hello. I have 3 questions. plz help

i am using ubuntu 18.04

1) i installed ambertools using with conda install -c conda-forge ambertools 
i was following the tutorial and xleap won't open 
when i type xleap the response is "xleap: command not found"
how is this fixed? 

2) i have nvidia gpu but is that utilised if i install ambertools from conda?

3) according to anaconda website, the ambertools version installed should be "v19.0" but that isn't what it says when i type "conda list" 
it shows ::
amberlite version 16.0
ambertools version 17.0 
why is this? 

thx!!!!

**Comment by hainm** [comment]
hi @tangkallisbak1, 

> when i type xleap the response is "xleap: command not found"

please install ambertools via its official channel "ambermd"
```
conda install ambertools -c ambermd
```

> i have nvidia gpu but is that utilised if i install ambertools from conda?

ambertools prebuild is for CPU only. Please check the notebook in the install page.
http://ambermd.org/GetAmber.php

> "conda list"

this shows the packages in your computer. I think you need to "anaconda search ambertools"
