### ISSUE TITLE
Charmmgen file missing in Anaconda package version > 17.6

### ISSUE THREAD

**Issue by lkagami** [Amber-MD/ambertools-binary-build#21]
Hi,
I missed the charmmgen file in versions higher than 17.6 in anaconda packages. 
Bests,
Luciano

**Comment by hainm** [comment]
@dacase is charmmgen turned off by default?

**Comment by hainm** [comment]
hi @lkagami  I've tracked down the amber mailing list and it's intentional to "hide" it.
http://archive.ambermd.org/201905/0313.html

**Comment by lkagami** [comment]
antechamber -fo charmm command does not build .inp and .rtf files.  This is due to charmmgen script absence. Thanks!
