### ISSUE TITLE
Unable to install AmberTools

### ISSUE THREAD

**Issue by kimlabSchatterjee** [Amber-MD/ambertools-binary-build#25]
am unable to install MPI and NON MPI verson of AmberTools in my system. It posses LinuxMint OS19.2 with intel i7 2700k processor and RTX 1060 GPU. the error is given bellow ...Please help

-- A library with LAPACK API not found. Please specify library location.
-- The ARPACK library was not found.  Please set ARPACK_LIBRARY to point to it. (missing: ARPACK_LIBRARY ARPACK_WORKS) 
-- Could not find some or all of the five main APBS libraries. Please set APBS_GENERIC_LIB, APBS_ROUTINES_LIB, 
APBS_PMGC_LIB, APBS_MG_LIB, and APBS_MALOC_LIB to point to the correct libraries (missing: APBS_API_LIB APBS_ROUTINES_LIB APBS_MG_LIB APBS_PMGC_LIB APBS_GENERIC_LIB APBS_MALOC_LIB APBS_WORKS APBS_INCLUDES) 
-- Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
-- Could not find the Java development libraries, so PUPIL can't be used. (missing: PUPIL_MAIN_LIB PUPIL_BLIND_LIB PUPIL_TIME_LIB) 
-- Could not find lio.  If you want to use it, set LIO_HOME to point to a built lio source directory.
-- Could NOT find PLUMED (missing: PLUMED_LIBRARY PLUMED_KERNEL_LIBRARY PLUMED_INCLUDES PLUMED_WORKS) (Required is at least version "2.5")
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Performing Test CMath_LINKS_WITHOUT_M
-- Performing Test CMath_LINKS_WITHOUT_M - Failed
-- Performing Test CMath_LINKS_WITH_M
-- Performing Test CMath_LINKS_WITH_M - Success
-- Found CMath: /usr/lib/x86_64-linux-gnu/libm.so  
-- Checking for perl module Chemistry::Mol
-- Checking for perl module Chemistry::Mol - failed
-- Checking for perl module ExtUtils::MakeMaker
-- Checking for perl module ExtUtils::MakeMaker - found at /usr/share/perl/5.26/ExtUtils/MakeMaker.pm
-- Failed to find Perl modules: Chemistry::Mol (missing: PERLMODULES_CHEMISTRY_MOL_MODULE) 
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   system
--   program_options
--   iostreams
--   regex
--   timer
--   chrono
--   filesystem
--   graph
--   date_time
--   atomic
-- Performing Test BOOST_SUPPORTS_COMPRESSION
-- Performing Test BOOST_SUPPORTS_COMPRESSION - Success
-- The following libraries were found on your system, but are not being used: boost
-- This is because the Amber devs have frequently seen broken installs of these libraries causing trouble.
-- To tell Amber to link to these libraries, you can select individual ones using -DFORCE_EXTERNAL_LIBS=<names>.
-- Alternatively, you can request that Amber link to all libraries it finds using -DTRUST_SYSTEM_LIBS=TRUE.
-- Cannot find PLUMED.  You will still be able to load it at runtime.  If you want to link it at build time, set PLUMED_ROOT to where you installed it.
CMake Error at cmake/3rdPartyTools.cmake:991 (message):
  Unable to build internal Boost without zlib and libbz2.
Call Stack (most recent call first):
  CMakeLists.txt:194 (include)

-- Configuring incomplete, errors occurred!
See also "/home/kimlab/Amber/amber20_src/build/CMakeFiles/CMakeOutput.log".

i installed boost liberary as well zlib libbz still it returns error

**Comment by hainm** [comment]
hi @kimlabSchatterjee: Please ask your question in amber mailing list. This repo is deprecated. http://ambermd.org/MailingLists.php
